import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Poppins } from 'next/font/google'
import "./globals.css";
import { Syne, Outfit } from 'next/font/google'
import NavbarComponent from "./Navbar/navbarComponent";
import { BackgroundRippleEffect } from "@/components/ui/background-ripple-effect";

import { DM_Sans } from 'next/font/google'

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-dm-sans',
})


const syne = Syne({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
  variable: '--font-syne',
})

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-outfit',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html
      lang="en"
      className={`${syne.variable} ${outfit.variable}  ${dmSans.variable}  h-full antialiased dark bg-neutral-primary scroll-smooth`}
    >
    
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <div className="z-30">
            {/* <NavbarComponent/> */}
        </div>
      <BackgroundRippleEffect/>
        {children}</body>
    </html>
  );
}
